apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/chereddynag/myservice.git'
    helm:
      valueFiles: []
    targetRevision: HEAD
    path: myservice
  destination:
    server:  'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
