apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocdapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocdapp
  template:
    metadata:
      labels:
        app: argocdapp
    spec:
      containers:
      - name: argocdapp
        image: us-west1-docker.pkg.dev/fluted-volt-428205-p7/chereddy/argocd:48
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
